apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: monitoring
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command:
    - /bin/sh
    - -c
    - >
      while true; do
        if ! command -v curl &> /dev/null; then
          echo "curl could not be found, installing...";
          apk --no-cache add curl;
        fi;
        curl http://nginx-service.monitoring.svc.cluster.local;
        sleep 1;
      done;
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
  restartPolicy: Never
