FROM golang:1.23.4-alpine3.20 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY api ./api
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/optiscaler ./cmd/optiscaler

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/optiscaler /optiscaler
USER 65532:65532
ENTRYPOINT ["/optiscaler"]
