serverFiles:
  prometheus.yaml:
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            action: replace
            regex: (.*)
            replacement: ${1}:9101
            target_label: __address__
