//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *DecisionRecord) DeepCopyInto(out *DecisionRecord) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.ObservedMetric != nil {
		in, out := &in.ObservedMetric, &out.ObservedMetric
		*out = new(float64)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	if in.ObservedTargetP95Milliseconds != nil {
		in, out := &in.ObservedTargetP95Milliseconds, &out.ObservedTargetP95Milliseconds
		*out = new(float64)
		**out = **in
	}
	if in.TargetRequestRate != nil {
		in, out := &in.TargetRequestRate, &out.TargetRequestRate
		*out = new(float64)
		**out = **in
	}
	if in.TargetSuccessfulRequestRate != nil {
		in, out := &in.TargetSuccessfulRequestRate, &out.TargetSuccessfulRequestRate
		*out = new(float64)
		**out = **in
	}
	if in.TargetErrorRate != nil {
		in, out := &in.TargetErrorRate, &out.TargetErrorRate
		*out = new(float64)
		**out = **in
	}
	if in.DependencyRequestRates != nil {
		in, out := &in.DependencyRequestRates, &out.DependencyRequestRates
		*out = make([]DependencyRequestRate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RejectedActions != nil {
		in, out := &in.RejectedActions, &out.RejectedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *DecisionRecord) DeepCopy() *DecisionRecord {
	if in == nil {
		return nil
	}
	out := new(DecisionRecord)
	in.DeepCopyInto(out)
	return out
}

func (in *DependencyRequestRate) DeepCopyInto(out *DependencyRequestRate) {
	*out = *in
	if in.RequestRate != nil {
		out.RequestRate = new(float64)
		*out.RequestRate = *in.RequestRate
	}
	if in.SuccessfulRequestRate != nil {
		out.SuccessfulRequestRate = new(float64)
		*out.SuccessfulRequestRate = *in.SuccessfulRequestRate
	}
	if in.ErrorRate != nil {
		out.ErrorRate = new(float64)
		*out.ErrorRate = *in.ErrorRate
	}
}

func (in *OptiScaler) DeepCopyInto(out *OptiScaler) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OptiScalerSpec) DeepCopyInto(out *OptiScalerSpec) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]DependencySpec, len(*in))
		copy(*out, *in)
	}
}

func (in *OptiScalerSpec) DeepCopy() *OptiScalerSpec {
	if in == nil {
		return nil
	}
	out := new(OptiScalerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DependencySpec) DeepCopyInto(out *DependencySpec) { *out = *in }
func (in *DependencySpec) DeepCopy() *DependencySpec {
	if in == nil {
		return nil
	}
	out := new(DependencySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OptiScaler) DeepCopy() *OptiScaler {
	if in == nil {
		return nil
	}
	out := new(OptiScaler)
	in.DeepCopyInto(out)
	return out
}

func (in *OptiScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OptiScalerList) DeepCopyInto(out *OptiScalerList) {
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptiScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OptiScalerList) DeepCopy() *OptiScalerList {
	if in == nil {
		return nil
	}
	out := new(OptiScalerList)
	in.DeepCopyInto(out)
	return out
}

func (in *OptiScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OptiScalerStatus) DeepCopyInto(out *OptiScalerStatus) {
	*out = *in
	if in.ObservedMetric != nil {
		in, out := &in.ObservedMetric, &out.ObservedMetric
		*out = new(float64)
		**out = **in
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastDecision != nil {
		out.LastDecision = in.LastDecision.DeepCopy()
	}
	if in.LastScaleDecision != nil {
		out.LastScaleDecision = in.LastScaleDecision.DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

func (in *OptiScalerStatus) DeepCopy() *OptiScalerStatus {
	if in == nil {
		return nil
	}
	out := new(OptiScalerStatus)
	in.DeepCopyInto(out)
	return out
}
